import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/form_data.module.css'
import axios from 'axios';
import Button from 'react-bootstrap/Button';
import Form from 'react-bootstrap/Form';
import 'bootstrap/dist/css/bootstrap.min.css';
import { useState } from "react";

export default function form() {

    const [name,setName]=useState('');
    const [address,setAddress]=useState('')
    const [email,setEmail]=useState('')
    const [password,setPassword]=useState('')
   
    const saveName = async() =>{
     let res = await axios.post('https://630857ae722029d9ddcc93c1.mockapi.io/form',{
     name: name,
     address: address,
     email: email,
     password: password
   
    })
    .then(function(response){
     console.leg('Stored successfully');
    })
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>FORM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <main className={styles.form_data}>
          <div>  <Form>
      <Form.Group className="mb-3" controlId="formBasicEmail">
        <Form.Label>Name</Form.Label>
        <Form.Control type="Name" placeholder="Enter Your Name" onChange={(e)=>{setName(e.target.value)}}/>
        <Form.Text className="text-muted">
        </Form.Text>
      </Form.Group>

      <Form.Group className="mb-3" controlId="formBasicPassword">
        <Form.Label>Address</Form.Label>
        <Form.Control type="Address" placeholder="Enter Your Name" onChange={(e)=>{setAddress(e.target.value)}}/>
      </Form.Group>
      <Form.Group className="mb-3" controlId="formBasicCheckbox">
        <Form.Group className="mb-3" controlId="formBasicEmail">
        <Form.Label>Email address</Form.Label>
        <Form.Control type="email" placeholder="Enter email" onChange={(e)=>{setEmail(e.target.value)}}/>
        <Form.Text className="text-muted">
        </Form.Text>
      </Form.Group>
      <Form.Group className="mb-3" controlId="formBasicPassword">
        <Form.Label>Password</Form.Label>
        <Form.Control type="password" placeholder="Password" onChange={(e)=>{setPassword(e.target.value)}}/>
      </Form.Group>
      <Form.Group className="mb-3" controlId="formBasicCheckbox">
        <Form.Check type="checkbox" label="Check me out" />
      </Form.Group>
      </Form.Group>     
      <Button variant="primary" onClick={saveName}>
        Submit
      </Button>
      
    </Form>
    </div>
      </main>
      </main>
    </div>
  )
}
